### PR TITLE
Update TenancyAppProvider.php

### PR DESCRIPTION
**Pull request by springleng**
```
>>> (new App\Providers\TenantWebsocketsProvider(app(Hyn\Tenancy\Repositories\WebsiteRepository::class)))->all()                                                                           
=> [                                                                                                                                                                                      
     BeyondCode\LaravelWebSockets\Apps\App {#3712                                                                                                                                         
       +id: "b9f65c07-3aaf-4c2d-8301-683c0a340365",                                                                                                                                       
       +key: "b9f65c07-3aaf-4c2d-8301-683c0a340365",                                                                                                                                      
       +secret: "eyJpdiI6ImhsRTM3TkF2em53UEZmZWhcLzFQb2VBPT0iLCJ2YWx1ZSI6Ikptd0pMdVo3dVQ3TU9QaWxqeXl6R3kzY0FaMnZxbU5GZU5rOGNlOFl2TG1Tc3FCc2tvRkZYcnB4VjBJcGFQemoiLCJtYWMiOiIwMzY0MjkzODI0M
zc3Njg1YTJmN2Y5MDNiODdjODIxMzExOGM2ZjU5NzgzNWYxOTMxOTcxMzIzMWFkODUxMGUzIn0=",                                                                                                             
       +name: null,                                                                                                                                                                       
       +host: null,                                                                                                                                                                       
       +clientMessagesEnabled: false,                                                                                                                                                     
       +statisticsEnabled: true,                                                                                                                                                          
     },                                                                                                                                                                                   
     BeyondCode\LaravelWebSockets\Apps\App {#3711                                                                                                                                         
       +id: "260581be-c51c-4868-91ab-e2f6ce4e5c28",                                                                                                                                       
       +key: "260581be-c51c-4868-91ab-e2f6ce4e5c28",                                                                                                                                      
       +secret: "eyJpdiI6IitxUEd4ZUdjRXk4TDZhUnRqcmJCbnc9PSIsInZhbHVlIjoiZ1JyYWlqdHBrXC9NWTBwMWY2eTdrcDZtaTZLOHBheWdxNWJHMDBsNXNCaUhWamc2NlwvZTIxR3B1eG92NkNZbU5nIiwibWFjIjoiMmE2MmVjMmZjY
mZmZDUxMjRhNjhmYTNiZTE1NDc4MzQ4NWI1YjdlNzIyNDhhNjRmMzUzMWZlM2I0YmNkYzBmZSJ9",                                                                                                             
       +name: null,                                                                                                                                                                       
       +host: null,                                                                                                                                                                       
       +clientMessagesEnabled: false,                                                                                                                                                     
       +statisticsEnabled: true,                                                                                                                                                          
     },                                                                                                                                                                                   
     BeyondCode\LaravelWebSockets\Apps\App {#3650                                                                                                                                         
       +id: "379a4bf7-95db-42c9-8274-6c0ed02db6c9",                                                                                                                                       
       +key: "379a4bf7-95db-42c9-8274-6c0ed02db6c9",                                                                                                                                      
       +secret: "eyJpdiI6ImhzclFDZjlHTGl6VzduazQ2bmJ4bXc9PSIsInZhbHVlIjoiXC8zYWVOU3NDWDRuczZwYzdMYUp5cFRzUVRxZStkUmZOR2NWWmpkdUNuajFkUFwvdjc3RzRFckcwVnBmTUErYlZiIiwibWFjIjoiOGRhZGQ2M2Q5N
2QzMWNmN2FlZjQxMmQ1NTU2YmUwNDAwYjgwMThjMTIyYjU3MTg5ZmY2MjA5NjNlMDAxZDJkMiJ9",                                                                                                             
       +name: null,                                                                                                                                                                       
       +host: null,                                                                                                                                                                       
       +clientMessagesEnabled: false,                                                                                                                                                     
       +statisticsEnabled: true,                                                                                                                                                          
     },                                                                                                                                                                                   
     BeyondCode\LaravelWebSockets\Apps\App {#3643                                                                                                                                         
       +id: "86b68dee-bf7c-4e65-aa91-3d30cdec6f32",                                                                                                                                       
       +key: "86b68dee-bf7c-4e65-aa91-3d30cdec6f32",                                                                                                                                      
       +secret: "eyJpdiI6ImpaOWF5VjA1cVRyMmFiekFiQjA4cUE9PSIsInZhbHVlIjoiaU1FTTJ6VGVqZ3VNN01mV3dDRm9hbjNSQkRcL3R2QWpLWEkwaCtxZXZPeURBVVwvY045aFVVeFpGOFJZNEtNVktPIiwibWFjIjoiOGJkYTIyZGE2M
jdkZDFlOTJjMjgxNDYzNjkwZjhiODM5NjYzNzkxOTJiNTA3ZTFkMDQ0MWQ4ZmIzZTNiZDRlMiJ9",                                                                                                             
       +name: null,                                                                                                                                                                       
       +host: null,                                                                                                                                                                       
       +clientMessagesEnabled: false,                                                                                                                                                     
       +statisticsEnabled: true,                                                                                                                                                          
     },                                                                                                                                                                                   
     BeyondCode\LaravelWebSockets\Apps\App {#3645                                                                                                                                         
       +id: "a6ef9ae7-1a50-4663-8e8f-96879d7190d3",                                                                                                                                       
       +key: "a6ef9ae7-1a50-4663-8e8f-96879d7190d3",                                                                                                                                      
       +secret: "eyJpdiI6Im5tdlR4UGZyZFgrS2hPUyt0ajVzXC93PT0iLCJ2YWx1ZSI6ImxWSlVKZlpPYXNwZ0hPWUdCTjh2Z2JcL3dcL2lQTjhSNmphaFVIdW5rbzBaQmc4dnBKdUxNbzhuNkdmdkI3dWd6ZSIsIm1hYyI6IjI3ZDUzYmU0Y
WRjMTcwMjBhZjVhMjYzMzRhYmMzYTRkZjk3ODJjYTkwMWZjODM4OTJmNmVjYTMyNmRhODc1ZmUifQ==",                                                                                                         
       +name: null,                                                                                                                                                                       
       +host: null,                                                                                                                                                                       
       +clientMessagesEnabled: false,                                                                                                                                                     
       +statisticsEnabled: true,                                                                                                                                                          
     },                                                                                                                                                                                   
     BeyondCode\LaravelWebSockets\Apps\App {#3632                                                                                                                                         
       +id: "336a0c8b-0efd-4337-b0ef-0af4db9a9747",                                                                                                                                       
       +key: "336a0c8b-0efd-4337-b0ef-0af4db9a9747",                                                                                                                                      
       +secret: "eyJpdiI6IjdhWDIyZ05zbnJWMzNha0VHRkZTVUE9PSIsInZhbHVlIjoiaHBzTnpCM05JTVBPcWR0eU4rMk9tMVpnSmVYXC8yZGs0eXZoOEZCMGtsbjZtQkRLR1cxNklKVTJaVW1GUFFDTUEiLCJtYWMiOiJkMWM2NGJmNmY0M
WUxODgzZmNjZTc0MjJiODc5ODI4YTdkNDczNWQyNmYxMWU3ZWNjZDQ4ZGM1NzZmZjI4YzIzIn0=",                                                                                                             
       +name: null,                                                                                                                                                                       
       +host: null,                                                                                                                                                                       
       +clientMessagesEnabled: false,                                                                                                                                                     
       +statisticsEnabled: true,                                                                                                                                                          
     },                                                                                                                                                                                   
   ]                                                                                                                                                                                      
>>>                                                                                                                                                                                       
```

### CODE REVIEW

**Comment by luceos** [comment]
Can you clarify what you are doing here? And why this change is necessary?

**Comment by springleng** [comment]
@luceos all function return array[BeyondCode\LaravelWebSockets\AppProviders\App]
```
interface AppProvider
{
    /**  @return array[BeyondCode\LaravelWebSockets\AppProviders\App] */
    public function all(): array;

    public function findByAppId(int $appId): ?App;

    public function findByAppKey(string $appKey): ?App;
}
```

**Comment by fletch3555** [comment]
I'm going to hold off on this.  I have some significant changes I've been working on (since I verified this doesn't work as-is)

**Comment by springleng** [comment]
@fletch3555 

Okay, Good job.

It really doesn't work properly. 

All tenants may be able to work properly with an appid, appkey, and appsecret.

**Pull request closed without merging**
